# services.yaml
services:
  vigihdev\WpDeregister\Contracts\DeregisterContract:
    public: true
    class: 'vigihdev\WpDeregister\Services\DeregisterService'
    arguments:
      $enqueueScriptsHandles:
        - "wp-deregister"
        - "wp-block-library-theme"
        - "wp-img-auto-sizes-contain"
        - "classic-theme-styles"
        - "global-styles"
        - "twentyten-block-style"
        - "wp-block-library"
        - "comment-reply"
      $filterHandles:
        - ["should_load_separate_core_block_assets", "__return_false"]
      $removeActionHandles:
        - ["wp_head", "print_emoji_detection_script", 7]
        - ["admin_print_scripts", "print_emoji_detection_script"]
        - ["wp_print_styles", "print_emoji_styles"]
        - ["admin_print_styles", "print_emoji_styles"]
